{
  "map": {
    "height": 10,
    "width": 17,
    "grid": [
      [
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 2,
              "id": 3,
              "capacity": 250,
              "weight": 50,
              "items": [
                {
                  "id": 2,
                  "quantity": 100
                },
                {
                  "id": 3,
                  "quantity": 17
                }
              ],
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        }
      ],
      [
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 4,
              "id": 2,
              "color": "#d10000"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 0,
              "id": 2,
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        }
      ],
      [
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 4,
              "id": 9,
              "color": "#d10000"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 3,
              "id": 5,
              "color": "#feea3a"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 4,
              "id": 3,
              "color": "#d10000"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 3,
              "id": 3,
              "color": "#feea3a"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        }
      ],
      [
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 2,
              "id": 1,
              "capacity": 250,
              "weight": 50,
              "items": [
                {
                  "id": 1,
                  "quantity": 10
                }
              ],
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        }
      ],
      [
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 0,
              "id": 1,
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 1,
              "id": 1,
              "color": "#FF0000",
              "load_cap": 200,
              "ip": "127.0.0.1",
              "port": "12345",
              "direction": 0,
              "deactivated": false
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 4,
              "id": 4,
              "color": "#d10000"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 4,
              "id": 5,
              "color": "#d10000"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        }
      ],
      [
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 3,
              "id": 1,
              "color": "#feea3a"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 4,
              "id": 8,
              "color": "#d10000"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 3,
              "id": 4,
              "color": "#feea3a"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        }
      ],
      [
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 4,
              "id": 7,
              "color": "#d10000"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        }
      ],
      [
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 2,
              "id": 2,
              "capacity": 250,
              "weight": 50,
              "items": [
                {
                  "id": 2,
                  "quantity": 100
                }
              ],
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        }
      ],
      [
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 3,
              "id": 2,
              "color": "#feea3a"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 4,
              "id": 6,
              "color": "#d10000"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        }
      ],
      [
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 0,
              "id": 3,
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 2,
              "id": 4,
              "capacity": 250,
              "weight": 50,
              "items": [
                {
                  "id": 3,
                  "quantity": 17
                },
                {
                  "id": 1,
                  "quantity": 17
                }
              ],
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        }
      ]
    ],
    "objects": {
      "1,1": [
        4,
        3
      ],
      "1,0": [
        4,
        1
      ],
      "1,3": [
        5,
        3
      ],
      "1,2": [
        3,
        12
      ],
      "2,2": [
        7,
        8
      ],
      "3,2": [
        0,
        7
      ],
      "4,2": [
        9,
        15
      ],
      "2,0": [
        1,
        15
      ],
      "3,0": [
        9,
        4
      ],
      "2,4": [
        1,
        8
      ],
      "3,4": [
        2,
        8
      ],
      "4,4": [
        4,
        6
      ],
      "5,4": [
        4,
        11
      ],
      "6,4": [
        8,
        10
      ],
      "7,4": [
        6,
        5
      ],
      "8,4": [
        5,
        7
      ],
      "9,4": [
        2,
        2
      ],
      "2,3": [
        8,
        3
      ],
      "3,3": [
        2,
        11
      ],
      "4,3": [
        5,
        9
      ],
      "5,3": [
        2,
        4
      ]
    }
  },
  "items": [
    {
      "id": 1,
      "weight": 1
    },
    {
      "id": 2,
      "weight": 1,
      "name": "Item#"
    },
    {
      "id": 3,
      "weight": 1,
      "name": "Item#"
    },
    {
      "id": 4,
      "weight": 1,
      "name": "Item#"
    }
  ],
  "nextIDs": {
    "gate": 4,
    "robot": 2,
    "rack": 5,
    "station": 6,
    "obstacle": 10,
    "item": 5
  }
}