{
  "map": {
    "height": "4",
    "width": "6",
    "grid": [
      [
        {
          "objects": [
            {
              "type": 1,
              "id": 1,
              "color": "#FF0000",
              "direction": 0,
              "load_cap": 100,
              "ip": "",
              "port": "",
              "deactivated": false
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 2,
              "id": 1,
              "capacity": 250,
              "weight": 50,
              "items": [
                {
                  "id": 1,
                  "quantity": 2
                }
              ],
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 0,
              "id": 1,
              "color": "#bababa"
            }
          ]
        }
      ],
      [
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 2,
              "id": 2,
              "capacity": 250,
              "weight": 50,
              "items": [
                {
                  "id": 1,
                  "quantity": 3
                }
              ],
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 2,
              "id": 3,
              "capacity": 250,
              "weight": 50,
              "items": [
                {
                  "id": 1,
                  "quantity": 4
                }
              ],
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        }
      ],
      [
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        }
      ],
      [
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 2,
              "id": 4,
              "capacity": 250,
              "weight": 50,
              "items": [
                {
                  "id": 1,
                  "quantity": 7
                }
              ],
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 2,
              "id": 5,
              "capacity": 250,
              "weight": 50,
              "items": [
                {
                  "id": 1,
                  "quantity": 1
                }
              ],
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 2,
              "id": 6,
              "capacity": 250,
              "weight": 50,
              "items": [],
              "color": "#bababa"
            }
          ]
        }
      ]
    ],
    "objects": {
      "1,0": [
        0,
        5
      ],
      "1,2": [
        0,
        2
      ],
      "2,2": [
        1,
        1
      ],
      "3,2": [
        1,
        3
      ],
      "4,2": [
        3,
        1
      ],
      "5,2": [
        3,
        3
      ],
      "6,2": [
        3,
        5
      ],
      "1,1": [
        0,
        0
      ]
    }
  },
  "items": [
    {
      "id": 1,
      "weight": 1,
      "name": "A"
    },
    {
      "id": 2,
      "weight": 2,
      "name": "B"
    },
    {
      "id": 3,
      "weight": 1,
      "name": "C"
    }
  ],
  "nextIDs": {
    "gate": 2,
    "robot": 2,
    "rack": 7,
    "station": 1,
    "obstacle": 1,
    "item": 1
  },
  "timestep": 0
}