{
  "map": {
    "height": "7",
    "width": "7",
    "grid": [
      [
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        }
      ],
      [
        {
          "objects": [
            {
              "type": 1,
              "id": 1,
              "color": "#FF0000",
              "direction": 0,
              "load_cap": 1000,
              "ip": "",
              "port": "",
              "deactivated": false
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 1,
              "id": 2,
              "color": "#FF0000",
              "direction": 0,
              "load_cap": 1000,
              "ip": "",
              "port": "",
              "deactivated": false
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        }
      ],
      [
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 2,
              "id": 1,
              "capacity": 250,
              "weight": 50,
              "items": [
                {
                  "id": 1,
                  "quantity": 100
                }
              ],
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 2,
              "id": 2,
              "capacity": 250,
              "weight": 50,
              "items": [
                {
                  "id": 2,
                  "quantity": 100
                }
              ],
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 0,
              "id": 1,
              "color": "#bababa"
            }
          ]
        }
      ],
      [
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        }
      ],
      [
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 2,
              "id": 3,
              "capacity": 250,
              "weight": 50,
              "items": [
                {
                  "id": 3,
                  "quantity": 100
                }
              ],
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        }
      ],
      [
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 1,
              "id": 3,
              "color": "#FF0000",
              "direction": 0,
              "load_cap": 1000,
              "ip": "",
              "port": "",
              "deactivated": false
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        }
      ],
      [
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 0,
              "id": 2,
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        }
      ]
    ],
    "objects": {
      "1,0": [
        2,
        6
      ],
      "2,0": [
        6,
        3
      ],
      "1,2": [
        2,
        1
      ],
      "2,2": [
        2,
        3
      ],
      "3,2": [
        4,
        2
      ],
      "1,1": [
        1,
        0
      ],
      "2,1": [
        1,
        3
      ],
      "3,1": [
        5,
        1
      ]
    }
  },
  "items": [
    {
      "id": 1,
      "weight": 1,
      "name": "A"
    },
    {
      "id": 2,
      "weight": 1,
      "name": "B"
    },
    {
      "id": 3,
      "weight": 1,
      "name": "C"
    }
  ],
  "nextIDs": {
    "gate": 3,
    "robot": 4,
    "rack": 4,
    "station": 1,
    "obstacle": 1,
    "item": 4
  },
  "timestep": 0
}