{
  "map": {
    "height": 7,
    "width": 7,
    "grid": [
      [
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 4,
              "id": 1,
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        }
      ],
      [
        {
          "objects": [
            {
              "type": 2,
              "id": 3,
              "capacity": 250,
              "weight": 50,
              "items": [
                {
                  "id": 3,
                  "quantity": 100
                }
              ],
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 4,
              "id": 3,
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 2,
              "id": 1,
              "capacity": 250,
              "weight": 50,
              "items": [
                {
                  "id": 1,
                  "quantity": 100
                }
              ],
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 0,
              "id": 1,
              "color": "#bababa"
            }
          ]
        }
      ],
      [
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 4,
              "id": 2,
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        }
      ],
      [
        {
          "objects": [
            {
              "type": 1,
              "id": 3,
              "color": "#FF0000",
              "direction": 0,
              "load_cap": 1000,
              "ip": "",
              "port": "",
              "deactivated": false
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 4,
              "id": 4,
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": [
            {
              "type": 2,
              "id": 4,
              "capacity": 250,
              "weight": 50,
              "items": [
                {
                  "id": 2,
                  "quantity": 100
                }
              ],
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        }
      ],
      [
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 4,
              "id": 5,
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 2,
              "id": 2,
              "capacity": 250,
              "weight": 50,
              "items": [
                {
                  "id": 1,
                  "quantity": 25
                }
              ],
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": [
            {
              "type": 1,
              "id": 1,
              "color": "#FF0000",
              "direction": 0,
              "load_cap": 1000,
              "ip": "",
              "port": "",
              "deactivated": false
            }
          ]
        }
      ],
      [
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 1,
              "id": 4,
              "color": "#FF0000",
              "direction": 0,
              "load_cap": 1000,
              "ip": "",
              "port": "",
              "deactivated": false
            }
          ]
        },
        {
          "objects": [
            {
              "type": 4,
              "id": 7,
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 1,
              "id": 2,
              "color": "#FF0000",
              "direction": 0,
              "load_cap": 1000,
              "ip": "",
              "port": "",
              "deactivated": false
            }
          ]
        },
        {
          "objects": []
        }
      ],
      [
        {
          "objects": [
            {
              "type": 0,
              "id": 2,
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": [
            {
              "type": 4,
              "id": 6,
              "color": "#bababa"
            }
          ]
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        },
        {
          "objects": []
        }
      ]
    ],
    "objects": []
  },
  "items": [
    {
      "id": 1,
      "weight": 1,
      "name": "A"
    },
    {
      "id": 2,
      "weight": 1,
      "name": "B"
    },
    {
      "id": 3,
      "weight": 1,
      "name": "C"
    }
  ],
  "nextIDs": {
    "gate": 3,
    "robot": 5,
    "rack": 5,
    "station": 1,
    "obstacle": 8,
    "item": 1
  },
  "timestep": 0
}